/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CPU_RS485.c
**     Project   : mcal
**     Processor : MC9S12XEP100MAG
**     Component : AsynchroSerial
**     Version   : Component 02.494, Driver 01.22, CPU db: 3.00.036
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2015-12-01, 11:13
**     Abstract  :
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
**     Settings  :
**         Serial channel              : SCI3
**
**         Protocol
**             Init baud rate          : 9600baud
**             Width                   : 8 bits
**             Stop bits               : 1
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 0
**             Output buffer size      : 0
**
**         Registers
**             Input buffer            : SCI3DRL   [$00C7]
**             Output buffer           : SCI3DRL   [$00C7]
**             Control register        : SCI3CR1   [$00C2]
**             Mode register           : SCI3CR2   [$00C3]
**             Baud setting reg.       : SCI3BD    [$00C0]
**             Special register        : SCI3SR1   [$00C4]
**
**         Input interrupt
**             Vector name             : Vsci3
**             Priority                : 4
**
**         Output interrupt
**             Vector name             : Vsci3
**             Priority                : 4
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     118              |  PM6_RxCAN3_RxCAN4_RxD3
**            Output  |     117              |  PM7_TxCAN3_TxCAN4_TxD3
**         ----------------------------------------------------------
**
**
**
**     Contents  :
**         Enable          - byte CPU_RS485_Enable(void);
**         Disable         - byte CPU_RS485_Disable(void);
**         EnableEvent     - byte CPU_RS485_EnableEvent(void);
**         DisableEvent    - byte CPU_RS485_DisableEvent(void);
**         RecvChar        - byte CPU_RS485_RecvChar(CPU_RS485_TComData *Chr);
**         SendChar        - byte CPU_RS485_SendChar(CPU_RS485_TComData Chr);
**         GetCharsInRxBuf - word CPU_RS485_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word CPU_RS485_GetCharsInTxBuf(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CPU_RS485. */

#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */
#pragma MESSAGE DISABLE C4301 /* INFORMATION C4301: Inline expansion done for function call */

#include "CPU_RS485.h"
#include "wdi.h"
#include "Timer.h"
#include "CAN0.h"
#include "CAN1.h"
#include "CAN4.h"
#include "CPU_CHG_S.h"
#include "CPU_CHG_P.h"
#include "ISO_CTRL_POS.h"
#include "ISO_CTRL_NEG.h"
#include "ISO_POW.h"
#include "CPUDI1.h"
#include "CPUDI2.h"
#include "CPUDI3.h"
#include "CPUDI4.h"
#include "OV_Power.h"
#include "UV_Power.h"
#include "CPU_SUMV_SDA.h"
#include "CPU_SUMV_SCL.h"

#include "CPU_SUMV_EXT_SDA.h"
#include "CPU_SUMV_EXT_SCL.h"
#include "CPU_SUMV_EXT_RDY.h"
#include "SUMV_EXT_POW.h"
#include "ExternFlash_Rst.h"
#include "ExternFlash_Cs.h"
#include "ExternFlash_Sck.h"
#include "ExternFlash_Si.h"
#include "ExternFlash_So.h"
#
#include "ExternTimer_Int.h"
#include "ExternTimer_Scl.h"
#include "ExternTimer_Sda.h"
#include "PORTA0.h"
#include "PORTA1.h"
#include "PORTA2.h"
#include "CON1.h"
#include "Slaver_Pow_Ctrl.h"
#include "CPU_RLY_POS.h"
#include "CPU_RLY_NEG.h"
#include "CPU_RLY_PRE.h"
#include "CPU_RLY_CHG.h"
#include "CPU_RLY_CTRL.h"
#include "RELAY_DIG_ST34.h"
#include "RELAY_DIG_ST12.h"
#include "AI1.h"
#include "AI2.h"
#include "CHG_CAN_POW.h"
#include "CPUCAN_CAR_EN.h"
#include "CPUCAN_INT_EN.h"
//#include "CURPOWER.h"
//#include "CPUCINT.h"
#include "CPUCSO.h"
#include "CPUCSI.h"
#include "CPUCSCK.h"
#include "CPUCCS.h"
#include "ExtEE_Sck.h"
#include "ExtEE_Sda.h"
#include "CPU_CAR_CAN_STB.h"
#include "CPU_CAR_CAN_ERR.h"
#include "ExtEE_Wp.h"
#include "AC_CP_IOC.h"
#include "RELAY_CHG.h"
#include "RELAY_PRE.h"
#include "RELAY_NEG.h"
#include "RELAY_POS.h"

#include "CPUDO2.h"
#include "CPUDO1.h"
#include "CPU_RLY_HEAT.h"
#include "CPU_RLY_FAN.h"
#include "CPUEE.h"
//#include "Timer_1ms.h"
#include "CPU_RS485_DR.h"
#include "RS485Events.h"

#pragma DATA_SEG CPU_RS485_DATA        /* Select data segment "CPU_RS485_DATA" */
#pragma CODE_SEG CPU_RS485_CODE



#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define COMMON_ERR       0x02U         /* Common error of RX       */
#define CHAR_IN_RX       0x04U         /* Char is in the RX buffer     */
#define FULL_TX          0x08U         /* Full transmit buffer     */

static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bit 0 - Overrun error */
                                       /* Bit 1 - Common error of RX */
                                       /* Bit 2 - Char in the RX buffer */
                                       /* Bit 3 - Full TX buffer */
static bool EnUser;                    /* Enable/Disable SCI */
volatile bool CPU_RS485_EnEvent;       /* Enable/Disable events */
static CPU_RS485_TComData BufferRead;  /* Input char for SCI commmunication */
static CPU_RS485_TComData BufferWrite; /* Output char for SCI commmunication */

/*
** ===================================================================
**     Method      :  CPU_RS485_Enable (component AsynchroSerial)
**
**     Description :
**         Enables the component - it starts the send and receive
**         functions. Events may be generated
**         ("DisableEvent"/"EnableEvent").
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte CPU_RS485_Enable(void)
{
  if(!EnUser) {                        /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    SCI3CR2 |= (SCI3CR2_TE_MASK | SCI3CR2_RE_MASK | SCI3CR2_RIE_MASK); /* Enable transmitter, Enable receiver, Enable receiver interrupt */
    if (SerFlag & FULL_TX) {           /* Is any char in the transmit buffer? */
        (void) SCI3SR1;                /* Reset interrupt request flag */
      while(SCI3SR1_TDRE == 0U) {}     /* Wait for transmitter empty */
      SCI3DRL = (byte)BufferWrite;     /* Store char to the transmitter register */
      SCI3CR2_TIE = 1U;                /* Enable transmit interrupt */
    }
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CPU_RS485_Disable (component AsynchroSerial)
**
**     Description :
**         Disables the component - it stops the send and receive
**         functions. No events will be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte CPU_RS485_Disable(void)
{
  if(EnUser) {                         /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    SCI3CR2 &= (byte)(~(byte)SCI3CR2_TIE_MASK) & (byte)(~(byte)SCI3CR2_RIE_MASK) & (byte)(~(byte)SCI3CR2_RE_MASK) & (byte)(~(byte)SCI3CR2_TE_MASK); /* Disable transmit interrupt, Disable receiver interrupt, Disable receiver, Disable transmitter */
  }
  return ERR_OK;                       /* OK */
}

/*
byte CPU_RS485_EnableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
byte CPU_RS485_DisableEvent(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  CPU_RS485_RecvChar (component AsynchroSerial)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/
byte CPU_RS485_RecvChar(CPU_RS485_TComData *Chr)
{
  byte Result = ERR_OK;                /* Return error code */

  if((SerFlag & CHAR_IN_RX) == 0U) {   /* Is any char in the RX buffer? */
    return ERR_RXEMPTY;                /* If no then error */
  }
  EnterCritical();                     /* Enter the critical section */
  *Chr = BufferRead;                   /* Received char */
  Result = (byte)((SerFlag & (OVERRUN_ERR|COMMON_ERR))?ERR_COMMON:ERR_OK);
  SerFlag &= (byte)(~(byte)(OVERRUN_ERR|COMMON_ERR|CHAR_IN_RX)); /* Clear all errors in the status variable */
  ExitCritical();                      /* Exit the critical section */
  return Result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  CPU_RS485_SendChar (component AsynchroSerial)
**
**     Description :
**         Sends one character to the channel. If the component is
**         temporarily disabled (Disable method) SendChar method only
**         stores data into an output buffer. In case of a zero output
**         buffer size, only one character can be stored. Enabling the
**         component (Enable method) starts the transmission of the
**         stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte CPU_RS485_SendChar(CPU_RS485_TComData Chr)
{
  if(SerFlag & FULL_TX) {              /* Is any char in the TX buffer */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Enter the critical section */
  if(EnUser) {                         /* Is the device enabled by user? */
    (void) SCI3SR1;                    /* Reset interrupt request flag */
    SCI3DRL = (byte)Chr;               /* Store char to transmitter register */
    SCI3CR2_TIE = 1U;                  /* Enable transmit interrupt */
  } else {
    BufferWrite = Chr;                 /* Store char to temporary variable */
  }
  SerFlag |= FULL_TX;                  /* Set the flag "full TX buffer" */
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  CPU_RS485_GetCharsInRxBuf (component AsynchroSerial)
**
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/
word CPU_RS485_GetCharsInRxBuf(void)
{
  return ((SerFlag & CHAR_IN_RX) ? (word)1U : (word)0U); /* Return number of chars in the receive buffer */
}
/*
** ===================================================================
**     Method      :  CPU_RS485_GetCharsInTxBuf (component AsynchroSerial)
**
**     Description :
**         Returns the number of characters in the output buffer. This
**         method is available only if the transmitter property is
**         enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the output
**                           buffer.
** ===================================================================
*/
word CPU_RS485_GetCharsInTxBuf(void)
{
  return ((SerFlag & FULL_TX) ? (word)1U : (word)0U); /* Return number of chars in the transmitter buffer */
}
/*
** ===================================================================
**     Method      :  CPU_RS485_InterruptRx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR         0x01U
#define ON_FULL_RX       0x02U
#define ON_RX_CHAR       0x04U
#define ON_RX_CHAR_EXT   0x10U
#pragma INLINE                         /* Directs the Compiler to inline the next function in the source */
static void CPU_RS485_InterruptRx(void)
{
  CPU_RS485_TComData Data;             /* Temporary variable for data */
  byte OnFlags = 0U;                   /* Temporary variable for flags */

  Data = SCI3DRL;                      /* Read data from the receiver */
  if(SerFlag & CHAR_IN_RX) {           /* Is a character already present in the receive buffer? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set flag OVERRUN_ERR */
    OnFlags |= ON_ERROR;               /* Set flag "OnError" */
  } else {
    BufferRead = Data;
    SerFlag |= CHAR_IN_RX;             /* Set flag "char in RX buffer" */
    OnFlags |= ON_RX_CHAR;             /* Set flag "OnRxChar" */
  }
  if(CPU_RS485_EnEvent) {              /* Are the events enabled? */
    if(OnFlags & ON_ERROR) {           /* Was an error detected? */
      CPU_RS485_OnError();             /* If yes then invoke user event */
    } else {
      if(OnFlags & ON_RX_CHAR) {       /* Is OnRxChar flag set? */
        CPU_RS485_OnRxChar();          /* If yes then invoke user event */
      }
    }
  }
}

/*
** ===================================================================
**     Method      :  CPU_RS485_InterruptTx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_FREE_TX  1U
#define ON_TX_CHAR  2U
#pragma INLINE                         /* Directs the Compiler to inline the next function in the source */
static void CPU_RS485_InterruptTx(void)
{
  byte OnFlags = 0U;                   /* Temporary variable for flags */

  if(SerFlag & FULL_TX) {              /* Is a char already present in the transmit buffer? */
    OnFlags |= ON_TX_CHAR;             /* Set flag "OnTxChar" */
  }
  SerFlag &= (byte)(~(byte)FULL_TX);   /* Reset flag "full TX buffer" */
  SCI3CR2_TIE = 0U;                    /* Disable transmit interrupt */
  if(CPU_RS485_EnEvent) {              /* Are the events enabled? */
    if(OnFlags & ON_TX_CHAR) {         /* Is flag "OnTxChar" set? */
      CPU_RS485_OnTxChar();            /* If yes then invoke user event */
    }
  }
}

/*
** ===================================================================
**     Method      :  CPU_RS485_Interrupt (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(CPU_RS485_Interrupt)
{
  byte StatReg = getReg(SCI3SR1);
  if (StatReg & (SCI3SR1_OR_MASK | SCI3SR1_FE_MASK | SCI3SR1_NF_MASK)) { /* Is any error flag set? */
    SerFlag |= COMMON_ERR;             /* If yes then set an internal flag */
    (void) SCI3DRL;                    /* Dummy read of data register - clear error bits */
    StatReg &= (byte)(~(byte)SCI3SR1_RDRF_MASK); /* Clear the receive data flag to discard the errorneous data */
    if(CPU_RS485_EnEvent) {            /* Are the events enabled? */
      CPU_RS485_OnError();             /* If yes then invoke user event */
    }
  }
  if (StatReg & SCI3SR1_RDRF_MASK) {   /* Is the receiver interrupt flag set? */
    CPU_RS485_InterruptRx();           /* If yes, then invoke the internal service routine. This routine is inlined. */
  }
  if (SCI3CR2_TIE) {                   /* Is the transmitter interrupt enabled? */
    if (StatReg & SCI3SR1_TDRE_MASK) { /* Is the transmitter interrupt flag set? */
      CPU_RS485_InterruptTx();         /* If yes, then invoke the internal service routine. This routine is inlined. */
    }
  }
}

#pragma CODE_SEG CPU_RS485_CODE
/*
** ===================================================================
**     Method      :  CPU_RS485_Init (component AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and internal 
**         variables of the component. The method is called automatically 
**         as a part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void CPU_RS485_Init(void)
{
  SerFlag = 0x00U;                     /* Reset flags */
  CPU_RS485_EnEvent = FALSE;           /* Disable events */
  EnUser = FALSE;                      /* Disable device */
  /* SCI3CR1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=1,PE=0,PT=0 */
  setReg8(SCI3CR1, 0x04U);              
  /* SCI3SR2: AMAP=1,??=0,??=0,TXPOL=0,RXPOL=0,BRK13=0,TXDIR=0,RAF=0 */
  setReg8(SCI3SR2, 0x80U);             /* Switch to the alternative register set */ 
  /* SCI3ASR1: RXEDGIF=1,??=0,??=0,??=0,??=0,BERRV=0,BERRIF=1,BKDIF=1 */
  setReg8(SCI3ASR1, 0x83U);            /* Clear alternative status flags */ 
  /* SCI3ACR1: RXEDGIE=0,??=0,??=0,??=0,??=0,??=0,BERRIE=0,BKDIE=0 */
  setReg8(SCI3ACR1, 0x00U);             
  /* SCI3ACR2: ??=0,??=0,??=0,??=0,??=0,BERRM1=0,BERRM0=0,BKDFE=0 */
  setReg8(SCI3ACR2, 0x00U);             
  /* SCI3SR2: AMAP=0,??=0,??=0,TXPOL=0,RXPOL=0,BRK13=0,TXDIR=0,RAF=0 */
  setReg8(SCI3SR2, 0x00U);             /* Switch to the normal register set */ 
  (void) SCI3SR1;                      /* Reset interrupt request flags */
  /* SCI3CR2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  SCI3CR2 = 0U;                        /* Disable error interrupts */
  SCI3BD = 0x0138U;                    /* Set prescaler bits */
  //Set prescaler bits  0138 4800  0x9CU 9600 4E 19200  27 38400
  SCI3CR2 &= (byte)(~(byte)SCI3CR2_TIE_MASK) & (byte)(~(byte)SCI3CR2_RIE_MASK) & (byte)(~(byte)SCI3CR2_RE_MASK) & (byte)(~(byte)SCI3CR2_TE_MASK); /* Disable transmit interrupt, Disable receiver interrupt, Disable receiver, Disable transmitter */
}



/* END CPU_RS485. */


/*
** ###################################################################
**
**     This file was created by Processor Expert 3.04 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
